"""Cria tabela gestao_documentos

Revision ID: bca4048f41dc
Revises: 
Create Date: 2025-11-03 20:31:48.763880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca4048f41dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestao_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('caminho', sa.String(length=300), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('criado_por', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gestao_documentos')
    # ### end Alembic commands ###
